{"cells":[{"cell_type":"markdown","metadata":{"id":"ORNxMOj3Tprs"},"source":["# Recursividad"]},{"cell_type":"markdown","metadata":{"id":"6UaRSFNmvqy3"},"source":["#### La **recursividad** ( o **recursión**) es la propiedad que posee un una  función de llamarse a sí misma. Una **función recursiva** es una función que se invoca a sí misma de forma *directa* o *indirecta*. En recursión directa el código de la función $f()$ contiene una sentencia que invoca a $f()$, mientras que en recursión indirecta $f()$ invoca a una  función $g()$ que invoca a su vez a la función $h()$, y así sucesivamente hasta que se invoca de nuevo a la función $f()$. Un requisito para que un algoritmo recursivo sea correcto es que no genere una secuencia infinita de llamadas sobre sí mismo ya que cualquier algoritmo que genere una secuencia de este tipo puede no terminar nunca.\n"]},{"cell_type":"markdown","metadata":{"id":"qr_xGQ68vqy4"},"source":["#### En matemáticas existen numerosas funciones que tienen carácter recursivo de igual modo numerosas circunstancias y situaciones de la vida ordinaria tienen carácter recursivo."]},{"cell_type":"markdown","metadata":{"id":"O9fW76U1vqy4"},"source":["## Recursión versus iteración"]},{"cell_type":"markdown","metadata":{"id":"XVfY2MLnvqy4"},"source":["#### Tanto la iteración como la recursión se basan en una ***estructura de control***: La iteración utiliza una ***estructura repetitiva***,  mientras que la recursión  utiliza una ***estructura de selección***.\n","\n","#### La iteración y la recursión implican ambas ***repetición***: la iteración utiliza explícitamente una estructura repetitiva, mientras que la iteración consigue la repetición mediante llamadas repetidas a funciones.\n","\n","#### La recursión invoca repetidamente al mecanismo de llamadas a funciones y en consecuencia se necesita un tiempo suplementario para  realizar cada llamada. Esta característica puede resultar cara en tiempo de procesador y espacio de memoria. La iteración se produce dentro de una función de modo que las operaciones suplementarias de las llamadas a la función y asignación de memoria adicional son omitidas.\n","\n","#### Se puede utilizar la recursividad como una alternativa a la iteración. La recursión es una herramienta poderosa e importante en la resolución de problemas y en programación. Una solución recursiva es normalmente menos eficiente en términos de tiempo de computadora que una solución iterativa debido a las operaciones auxiliares que llevan consigo las llamadas suplementarias a las funciones; sin embargo, en muchas circunstancias el uso de la recursión permite a los programadores especificar soluciones naturales, sencillas, que serían, en caso contrario, difíciles de resolver. La razón fundamental para elegir la recursión es que existen numerosos problemas complejos que poseen naturaleza recursiva y, en consecuencia, son más fáciles de diseñar e implementar con algoritmos de este tipo."]},{"cell_type":"markdown","metadata":{"id":"dLqotzVEvqy4"},"source":["## Ejemplo\n","\n","#### Escribe una función recursiva en Python que reciba como argumento un número entero positivo $n$ y determine  el factorial de $n$.\n","#### **Solución:**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_sHmaBLBvqy4"},"outputs":[],"source":["def factorial(n):\n","    if n == 0:\n","        return 1\n","    else:\n","        return n * factorial(n-1)\n","\n","n = int(input('Ingresa un número entero positivo'))\n","print(f\"El factorial de {n} es: {factorial(n)} \")"]},{"cell_type":"markdown","metadata":{"id":"g6l0jtd3vqy5"},"source":["## Ejemplo\n","\n","#### Escribe una función recursiva en Python que reciba como argumento un número entero positivo $n$ y determine  la suma de los primeros $n$ números enteros positivos.\n","\n","#### **Solución:**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fqSBOvuGvqy5"},"outputs":[],"source":["def suma_gauss(n):\n","    if n == 1:\n","        return 1\n","    else:\n","        return n + suma_gauss(n-1)\n","\n","n = int(input('Ingresa un número entero positivo'))\n","print(f\"La suma de los primeros {n} números enteros positivos es: {suma_gauss(n)} \")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Fp3NK5uevqy6"},"outputs":[],"source":[]},{"cell_type":"markdown","metadata":{"id":"qY22F8_Hvqy6"},"source":["## Ejemplo\n","\n","#### Escribe una función recursiva en Python que reciba como argumento un número entero positivo $n$ y determine $n$-ésimo término de la sucesión de Fibonacci.\n","\n","#### **Solución**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"NRItDcC3vqy6"},"outputs":[],"source":["def nfibo(n):\n","    if n == 1 or n == 2:\n","        return 1\n","    else:\n","        return nfibo(n-1) + nfibo(n-2)\n","\n","n = int(input('Ingresa un número entero positivo'))\n","\n","print(f\"El {n}-ésimo término de la sucesión de Fibonacci es: {nfibo(n)} \")"]},{"cell_type":"markdown","metadata":{"id":"ftwC8plAvqy6"},"source":["## Ejemplo\n","\n","#### Escribe una función recursiva en Python que reciba como argumento un número entero positivo $n$ y determine su correespondiente expresión en binario.\n","\n","### Solución:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"MrbFhTlevqy6"},"outputs":[],"source":["def dec_bin(n):\n","    if n//2 == 0:\n","        return str(n%2)\n","    else:\n","        return dec_bin(n//2) + str(n%2)\n","\n","print(dec_bin(2))"]},{"cell_type":"markdown","metadata":{"id":"N4UoEQxcvqy6"},"source":["## Ejemplo\n","\n","#### Escribe una función recursiva en Python que reciba como argumento dos números enteros positivos $a$ y $b$  y determine el producto $a \\times b$\n","\n","### Solución:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TLv-gJaavqy6"},"outputs":[],"source":["def producto_sumando(a,b):\n","    if  a == 0:\n","        return 0\n","    else:\n","        return b + producto_sumando(a-1,b)\n","\n","\n","print(producto_sumando(0,0))"]},{"cell_type":"markdown","metadata":{"id":"2WvDTGf65ypL"},"source":["## Ejemplo\n","\n","### Solución:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Enbwxz5F1lNY"},"outputs":[],"source":["def producto_sumando(a,b):\n","    if  b == 0:\n","        return 0\n","    else:\n","        return a + producto_sumando(b-1,a)\n","\n"]},{"cell_type":"markdown","metadata":{"id":"fJNr1czU5ypM"},"source":["## Ejemplo\n","\n","### Solución:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"JIpCuhsK5k7O"},"outputs":[],"source":["def var_abs(n):\n","  if n>=0:\n","    return n\n","  else:\n","     return var_abs(-n)\n","\n","print(var_abs(5))"]},{"cell_type":"markdown","metadata":{"id":"Cbm_3jlPvqy6"},"source":["# **Errores y excepciones**\n"]},{"cell_type":"markdown","metadata":{"id":"-gNo7jzuvqy6"},"source":["#### En un programa podemos encontrarnos con distintos tipos de errores pero a grandes rasgos podemos decir que todos los errores pertenecen a una de las siguientes categorías."]},{"cell_type":"markdown","metadata":{"id":"5-sW0QNavqy6"},"source":["\n","#### ***Errores de sintaxis:*** estos errores son seguramente los más simples de resolver, pues son detectados por el intérprete (o por el compilador, según el tipo de lenguaje que estemos utilizando) al procesar el código fuente y generalmente son consecuencia de equivocaciones al escribir el programa. En el caso de Python estos errores son indicados con un mensaje `SyntaxError`. Por ejemplo, si trabajando con Python intentamos definir una función y en lugar de `def` escribimos `dev`.\n","\n","#### ***Errores semánticos:*** se dan cuando un programa, a pesar de no generar mensajes de error, no produce el resultado esperado. Esto puede deberse, por ejemplo, a un algoritmo incorrecto o a la omisión de una sentencia.\n","\n","#### ***Errores de ejecución:*** estos errores aparecen durante la ejecución del programa y su origen puede ser diverso. En ocasiones pueden producirse por un uso incorrecto del programa por parte del usuario, por ejemplo si el usuario ingresa una cadena cuando se espera un número. En otras ocasiones pueden deberse a errores de programación, por ejemplo si una función intenta acceder a la quinta posición de una lista de 3 elementos o realizar una división por cero. Una causa común de errores de ejecución que generalmente excede al programador y al usuario, son los recursos externos al programa, por ejemplo si el programa intenta leer un archivo y el mismo se encuentra dañado.\n"]},{"cell_type":"markdown","metadata":{"id":"vAcXcDipvqy6"},"source":["#### Tanto a los errores de sintaxis como a los semánticos se los puede detectar y corregir durante la construcción del programa ayudados por el intérprete y la ejecución de pruebas. Pero no ocurre esto con los ***errores de ejecución*** ya que ***no siempre es posible saber cuando ocurrirán*** y puede resultar muy complejo (o incluso casi imposible) reproducirlos. Es por ello nos centraremos en cómo ***preparar nuestros programas para lidiar con este tipo de errores***."]},{"cell_type":"markdown","metadata":{"id":"QgF3mZGQvqy6"},"source":["#### Los ***errores de ejecución*** son llamados comúnmente **excepciones**. Durante la ejecución de un programa, si dentro de una función surge una excepción y la función no la *maneja*, la excepción se propaga hacia la función que la invocó, si esta otra tampoco la *maneja*, la excepción continua propagándose hasta llegar a la función inicial del programa y si esta tampoco la *maneja* se interrumpe la ejecución del programa."]},{"cell_type":"markdown","metadata":{"id":"h-3ARms-vqy7"},"source":["## **Excepciones en Python**"]},{"cell_type":"markdown","metadata":{"id":"aeXkV3A_vqy7"},"source":["\n","#### Las ***excepciones*** en Python son una herramienta muy potente, se trata de una forma de ***controlar el comportamiento de un programa cuando se produce un error***.\n","\n","#### Esto es muy importante ya que salvo que tratemos este error, el programa se detendrá, y esto es algo que en determinadas aplicaciones no es una opción válida."]},{"cell_type":"markdown","metadata":{"id":"2S__f9kB5ypM"},"source":["### **Ejemplo**"]},{"cell_type":"markdown","metadata":{"id":"_69Wfuhqvqy7"},"source":["#### Imaginemos que tenemos el siguiente código con dos variables `a` y `b` y realizamos su división `a/b`."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":2,"status":"ok","timestamp":1709831791943,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"hY4MaGkuvqy7","outputId":"5cb0ba24-14b6-4d62-e13b-861bb214de4a"},"outputs":[{"name":"stdout","output_type":"stream","text":["2.0\n"]}],"source":["a = 4\n","b = 2\n","c = a/b\n","print(c)\n"]},{"cell_type":"markdown","metadata":{"id":"8hEG_Atdvqy7"},"source":["#### Pero imaginemos ahora que por cualquier motivo las variables tienen otro valor, y que por ejemplo `b` tiene el valor `0`. **Si intentamos hacer la división entre cero**, este programa dará un error y su ejecución terminará de manera abrupta."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":176},"executionInfo":{"elapsed":287,"status":"error","timestamp":1709831804100,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"U8y6vqY9vqy7","outputId":"2414df1d-17ec-4d61-a6fc-eef7ccae99e3"},"outputs":[{"ename":"ZeroDivisionError","evalue":"division by zero","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-39f2597838d5>\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["a = 4\n","b = 0\n","print(a/b)"]},{"cell_type":"markdown","metadata":{"id":"hUHHp1_6vqy7"},"source":["#### Ese *error* que decimos que ha ocurrido es lanzado por Python ya que la división entre cero es una operación que matemáticamente no está definida. Se trata de la excepción` ZeroDivisionError`."]},{"cell_type":"markdown","metadata":{"id":"lhuyYHHG5ypM"},"source":["### **Ejemplo**"]},{"cell_type":"markdown","metadata":{"id":"SP0z79Mkvqy7"},"source":["#### **Veamos un ejemplo con otra excepción**. ¿Que pasaría si intentásemos sumar un número con un texto? Evidentemente esto no tiene ningún sentido, y Python define una excepción para esto llamada `TypeError`."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"elapsed":282,"status":"error","timestamp":1709832030547,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"TOyFhzgJvqy7","outputId":"c8434c03-6b3b-4bae-e3aa-5fd01b5e0c1b"},"outputs":[{"ename":"TypeError","evalue":"unsupported operand type(s) for +: 'int' and 'str'","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-96788054896b>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m\"2\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}],"source":["print(2 + \"2\")"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":159},"executionInfo":{"elapsed":4389,"status":"error","timestamp":1709832065839,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"92F9drTYvqy7","outputId":"bd544f73-c17f-4668-a289-95983f86cff7"},"outputs":[{"name":"stdout","output_type":"stream","text":["Ingresa un numerop\n"]},{"ename":"ValueError","evalue":"invalid literal for int() with base 10: 'p'","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-fe680dff7e4c>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mx\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Ingresa un numero'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'p'"]}],"source":["x=int(input('Ingresa un numero'))"]},{"cell_type":"markdown","metadata":{"id":"__HELWIyvqy7"},"source":["#### Es muy importante controlar las excepciones, porque por muchas comprobaciones que realicemos es posible que en algún momento ocurra una, y si no se hace nada el programa se detendrá."]},{"cell_type":"markdown","metadata":{"id":"8TcV7uQ3vqy7"},"source":["#### **¿Puedes imaginar que en un avión, el metro de la CDMX o un cajero automático ocurra un error y se detenga por completo?**"]},{"cell_type":"markdown","metadata":{"id":"AcoTIEagvqy7"},"source":[" ## **Manejo de excepciones**"]},{"cell_type":"markdown","metadata":{"id":"TYtbWzkwvqy7"},"source":["#### Una primera aproximación al control de excepciones podría ser el siguiente ejemplo. Podemos realizar una comprobación manual de que no estamos dividiendo por cero, para así evitar tener un error tipo `ZeroDivisionError`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"PGnGXyRmvqy7"},"outputs":[],"source":["a = 5\n","b = 0\n","if b!=0:\n","    print(a/b)\n","else:\n","    print(\"No se puede dividir!\")"]},{"cell_type":"markdown","metadata":{"id":"8gqgNTs8vqy7"},"source":["#### Para el **manejo de excepciones** Python provee ciertas palabras reservadas, que nos permiten manejar las excepciones que puedan surgir y tomar acciones de recuperación para evitar la interrupción del programa o, al menos, para realizar algunas acciones adicionales antes de interrumpir el programa."]},{"cell_type":"markdown","metadata":{"id":"XJe0pCD5vqy7"},"source":["#### En el caso de Python, el **manejo de excepciones** se hace mediante los bloques que utilizan las sentencias `try`, `except` y `finally`"]},{"cell_type":"markdown","metadata":{"id":"jm2Vn8q-vqy7"},"source":["# Sentencias `try` - `except`"]},{"cell_type":"markdown","metadata":{"id":"0Tm-M0v-vqy-"},"source":["#### Las excepciones que hemos visto antes, pueden ser capturadas y manejadas adecuadamente, sin que el programa se detenga. Veamos un ejemplo con la división entre cero."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":293,"status":"ok","timestamp":1709832234744,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"6i3ibNjvvqy-","outputId":"c3136bc8-f3dd-436f-d417-1f3781903346"},"outputs":[{"name":"stdout","output_type":"stream","text":["¡No se ha podido realizar la división, division entre cero!\n"]}],"source":["a = 5; b = 0\n","try:\n","    c = a/b\n","    print(c)\n","except:\n","    print(\"¡No se ha podido realizar la división, division entre cero!\")"]},{"cell_type":"markdown","metadata":{"id":"KU5hch5rvqy-"},"source":["#### En este caso, se levantó la excepción `ZeroDivisionError` cuando se quiso hacer la división. Para evitar que se levante la excepción y se detenga la ejecución del programa, se utiliza el bloque `try-except`."]},{"cell_type":"markdown","metadata":{"id":"xAVL1O3ovqy-"},"source":["#### En este caso no verificamos que `b!=0`. Directamente intentamos realizar la división y en el caso de que se lance la excepción `ZeroDivisionError`, la ***capturamos*** y la ***tratamos*** adecuadamente."]},{"cell_type":"markdown","metadata":{"id":"j472PJF9vqy-"},"source":["* ####  La sentencia `try` **contiene el bloque de código que puede *ocasionar* o *levantar* una excepción** o un error. Se utiliza el término levantar para referirse a la acción de generar una excepción.\n","\n","* ####  A continuación se ubica el bloque `except`, que se encarga de capturar la excepción y nos da la oportunidad de procesarla mostrando por ejemplo un mensaje adecuado al usuario. **Contiene el bloque de código que se ejecutará si y sólo si un error es detectado** en nuestro código."]},{"cell_type":"markdown","metadata":{"id":"8pYzCRl6vqy-"},"source":["### **Ejemplo**\n","\n","#### Las siguientes líneas de código siguiente nos dará error si el usuario introduce letras en lugar de números:  "]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":176},"executionInfo":{"elapsed":7647,"status":"error","timestamp":1709832351318,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"ShegHi5Pvqy-","outputId":"bcf5dd71-a0b9-43bc-9fb0-8187d8b6601e"},"outputs":[{"name":"stdout","output_type":"stream","text":["¿Cuantos años tienes?pablo\n"]},{"ename":"ValueError","evalue":"invalid literal for int() with base 10: 'pablo'","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-2b43d4437e0a>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mnum\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'¿Cuantos años tienes?'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Tienes  {num} años'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'pablo'"]}],"source":["num=int(input('¿Cuantos años tienes?'))\n","print(f'Tienes  {num} años')"]},{"cell_type":"markdown","metadata":{"id":"XO2UjIpEvqy_"},"source":["#### Por lo tanto podemos implementar la sentencia `try-except`:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":419},"executionInfo":{"elapsed":17414,"status":"error","timestamp":1709832431525,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"3SqVsXzyvqy_","outputId":"c3d66e0d-53bd-4232-964b-4d1f8894ed67"},"outputs":[{"name":"stdout","output_type":"stream","text":["¿Cuantos años tienes?Daniel\n","Tipo de dato incorrecto\n","¿Cuantos años tienes?Jorge\n"]},{"ename":"ValueError","evalue":"invalid literal for int() with base 10: 'Jorge'","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-9-061c6669f67d>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mnum\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'¿Cuantos años tienes?'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Tienes  {num} años'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'Daniel'","\nDuring handling of the above exception, another exception occurred:\n","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-9-061c6669f67d>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mexcept\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Tipo de dato incorrecto'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m     \u001b[0mnum\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'¿Cuantos años tienes?'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Tienes  {num} años'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'Jorge'"]}],"source":["try:\n","    num=int(input('¿Cuantos años tienes?'))\n","    print(f'Tienes  {num} años')\n","except:\n","    print('Tipo de dato incorrecto')\n","    num=int(input('¿Cuantos años tienes?'))\n","    print(f'Tienes  {num} años')"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":8008,"status":"ok","timestamp":1709833369070,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"QtJyfIY0_-3o","outputId":"e2c49343-486f-44de-d5b6-f7ea48c9a906"},"outputs":[{"name":"stdout","output_type":"stream","text":["Tipo de dato incorrecto\n","¿Cuantos años tienes?15\n","Tienes  15 años\n"]}],"source":["from google.colab import output\n","\n","def datos():\n","  try:\n","      num=int(input('¿Cuantos años tienes?'))\n","      print(f'Tienes  {num} años')\n","  except:\n","      output.clear()\n","      print('Tipo de dato incorrecto')\n","      datos()\n","\n","datos()"]},{"cell_type":"markdown","metadata":{"id":"ApSXmNmFvqy_"},"source":["## Multiples excepciones"]},{"cell_type":"markdown","metadata":{"id":"mGXLnqNxvqy_"},"source":["#### Dado que dentro de un mismo bloque `try` pueden producirse excepciones de distinto tipo, es posible utilizar varios bloques `except`, cada uno para capturar un tipo distinto de excepción."]},{"cell_type":"markdown","metadata":{"id":"p47b5HXvvqy_"},"source":["#### En algunas ocasiones dentro de un mismo bloque `try` pueden producirse excepciones de distinto tipo y será necesario agregar **multiples excepciones**, para esto es posible utilizar varios bloques `except`, cada uno para capturar un tipo *distinto de excepción*.\n","\n","#### Esto se hace especificando a continuación de la sentencia `except` el nombre de la excepción (Python cuenta con palabras reservadas para *clasificar el tipo de error*) que se pretende capturar. Un mismo bloque `except` puede atrapar varios tipos de excepciones, lo cual se hace especificando los nombres de la excepciones separados por comas y entre parentesis a continuación de la palabra `except`. Es importante destacar que si bien luego de un bloque `try` puede haber varios bloques `except`, se ejecutará, a lo más uno de ellos."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":276,"status":"ok","timestamp":1709832777143,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"AppfYXybvqy_","outputId":"c83fc89c-adf5-435a-c64a-fd3d4aae3827"},"outputs":[{"name":"stdout","output_type":"stream","text":["Enconntre un problema que no se resolver!\n"]}],"source":["try:\n","    #c = 5/0\n","    #d = 2 + \"Hola\"\n","    lista = [1]\n","    print(lista[1])\n","except ZeroDivisionError:\n","    print(\"No se puede dividir entre cero!\")\n","except TypeError:\n","    print(\"Problema de tipos!\")\n","except:\n","    print(\"Enconntre un problema que no se resolver!\")"]},{"cell_type":"markdown","metadata":{"id":"g_fAiCOwvqy_"},"source":["#### Puedes también hacer que un determinado número de excepciones se traten de la misma manera con el mismo bloque de código. Sin embargo suele ser más interesante tratar a diferentes excepciones de diference manera."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":298,"status":"ok","timestamp":1709833573648,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"naj4-R8Tvqy_","outputId":"012e165e-9e5b-44a9-e0b0-bdf32f142170"},"outputs":[{"name":"stdout","output_type":"stream","text":["Excepcion ZeroDivisionError o TypeError\n"]}],"source":["try:\n","    #c = 5/0\n","    d = 2 + \"Hola\"\n","except (ZeroDivisionError, TypeError):\n","    print(\"Excepcion ZeroDivisionError o TypeError\")"]},{"cell_type":"markdown","metadata":{"id":"ZotVJjfAvqy_"},"source":["#### Si no sabes que excepción puede saltar, puedes usar la clase genérica `Exception`. En este caso se controla cualquier tipo de excepción. De hecho todas las excepciones heredan de `Exception`."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":380,"status":"ok","timestamp":1709833620696,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"1ZUUi114vqy_","outputId":"8377f05d-c979-40ef-ac58-7a3e8471afeb"},"outputs":[{"name":"stdout","output_type":"stream","text":["Ha ocurrido una excepción\n"]}],"source":["try:\n","    #c = 5/0\n","    d = 2 + \"Hola\"\n","except Exception:\n","    print(\"Ha ocurrido una excepción\")"]},{"cell_type":"markdown","metadata":{"id":"R4BUFoFKvqy_"},"source":["#### No obstante hay una forma de saber que excepción ha sido la que ha ocurrido."]},{"cell_type":"markdown","metadata":{"id":"X0LUwaGEB_fQ"},"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":493,"status":"ok","timestamp":1709833747960,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"},"user_tz":360},"id":"7vb-FJ4Avqy_","outputId":"4f3ac229-10b3-494b-8da2-ed946e0e5e80"},"outputs":[{"name":"stdout","output_type":"stream","text":["Ha habido una excepción <class 'AttributeError'>\n"]}],"source":["try:\n","   lista = [1,2]\n","   print(lista.ms())\n","except Exception as ex:\n","    print(\"Ha habido una excepción\", type(ex))\n"]},{"cell_type":"markdown","metadata":{"id":"jZ1EXTNpGXbU"},"source":["<table>\n","  <tr>\n","    <th>Error</th>\n","    <th>Descripción</th>\n","    <th>Ejemplo</th>\n","  </tr>\n","  <tr>\n","    <td>ArithmeticError</td>\n","    <td>Clase base para errores aritméticos</td>\n","    <td>1 / 0</td>\n","  </tr>\n","  <tr>\n","    <td>AssertionError</td>\n","    <td>Error lanzado cuando una instrucción assert falla</td>\n","    <td>assert False, \"Este es un mensaje de error personalizado\"</td>\n","  </tr>\n","  <tr>\n","    <td>AttributeError</td>\n","    <td>Error lanzado cuando un objeto no tiene un atributo válido</td>\n","    <td>objeto.atributo_invalido</td>\n","  </tr>\n","  <tr>\n","    <td>EOFError</td>\n","    <td>Error lanzado cuando se alcanza el final del archivo</td>\n","    <td>input() (presionar Ctrl + D para generar el error)</td>\n","  </tr>\n","  <tr>\n","    <td>ImportError</td>\n","    <td>Error lanzado cuando no se puede importar un módulo</td>\n","    <td>import modulo_inexistente</td>\n","  </tr>\n","  <tr>\n","    <td>IndexError</td>\n","    <td>Error lanzado cuando un índice de secuencia es fuera de rango</td>\n","    <td>lista = [1, 2, 3]; lista[3]</td>\n","  </tr>\n","  <tr>\n","    <td>KeyError</td>\n","    <td>Error lanzado cuando una clave no se encuentra en un diccionario</td>\n","    <td>diccionario = {\"clave\": \"valor\"}; diccionario[\"clave_invalida\"]</td>\n","  </tr>\n","  <tr>\n","    <td>NameError</td>\n","    <td>Error lanzado cuando no se encuentra un nombre o símbolo local o global</td>\n","    <td>nombre_invalido</td>\n","  </tr>\n","  <tr>\n","    <td>TypeError</td>\n","    <td>Error lanzado cuando un operando o argumento tiene un tipo incorrecto</td>\n","    <td>5 + \"cadena\"</td>\n","  </tr>\n","  <tr>\n","    <td>ValueError</td>\n","    <td>Error lanzado cuando un operando o argumento tiene un valor incorrecto</td>\n","    <td>int(\"cadena\")</td>\n","  </tr>\n","  <tr>\n","    <td>ZeroDivisionError</td>\n","    <td>Error lanzado cuando se intenta dividir por cero</td>\n","    <td>1 / 0</td>\n","  </tr>\n","</table>"]},{"cell_type":"markdown","source":["## Ejemplo"],"metadata":{"id":"xrpSfctSGg3b"}},{"cell_type":"code","source":["from google.colab import output\n","import time\n","\n","def check_entero():\n","  try:\n","    n = int(input(\" Ingresa un número entero \"))\n","  except ValueError:\n","    print(\"¡Debes ingresar un número entero!\")\n","    time.sleep(2.5)\n","    output.clear()\n","    check_entero()\n","\n","check_entero()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"UxkvD2b6GjN7","executionInfo":{"status":"ok","timestamp":1709919214273,"user_tz":360,"elapsed":35596,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"}},"outputId":"90f131b8-f66d-4b51-f847-b9c7d6d22883"},"execution_count":null,"outputs":[{"name":"stdout","output_type":"stream","text":["Ingresa un número entero5\n"]}]},{"cell_type":"code","source":["def check_funcion(nombre_archivo):\n","  try:\n","    archivo=open(nombre_archivo,'r')\n","    contenido = archivo.read()\n","    print(\"El contenido del archivo es:\")\n","    print(contenido)\n","  except FileNotFoundError:\n","    print(\"El archivo no fue encontrado\")\n","\n","check_funcion(\"/content/mi_archivo_.txt\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"xyXy-QwbHXr5","executionInfo":{"status":"ok","timestamp":1709919694079,"user_tz":360,"elapsed":149,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"}},"outputId":"3bab1c96-97df-4df3-f4c6-b2109b541b17"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["El archivo no fue encontrado\n"]}]},{"cell_type":"markdown","source":[],"metadata":{"id":"KIrHb7wfKlOm"}},{"cell_type":"code","source":["def check_archivo(ruta,modo):\n","  try:\n","    archivo = open(ruta,modo)\n","    archivo.write(\"Esto es una nueva linea\")\n","    archivo.close()\n","  except FileNotFoundError:\n","    print(\"El archivo no fue encontrado\")\n","  except UnsupportedOperation:\n","    print(\"No puedes escribir en un archivo de solo lectura\")\n","\n","check_archivo(\"/content/archivo_error_permiso.txt\",'r')\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":297},"id":"XPF5StrmLtnH","executionInfo":{"status":"error","timestamp":1709920699918,"user_tz":360,"elapsed":226,"user":{"displayName":"PABLO JORGE HERNANDEZ HERNANDEZ","userId":"08090470510402532817"}},"outputId":"df437163-f5a7-4759-a7fa-c516196043d2"},"execution_count":8,"outputs":[{"output_type":"error","ename":"UnsupportedOperation","evalue":"not writable","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mUnsupportedOperation\u001b[0m                      Traceback (most recent call last)","\u001b[0;32m<ipython-input-8-cb26be885867>\u001b[0m in \u001b[0;36m<cell line: 11>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      9\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"No puedes escribir en un archivo de solo lectura\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m \u001b[0mcheck_archivo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"/content/archivo_error_permiso.txt\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m'r'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-8-cb26be885867>\u001b[0m in \u001b[0;36mcheck_archivo\u001b[0;34m(ruta, modo)\u001b[0m\n\u001b[1;32m      2\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m     \u001b[0marchivo\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mruta\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mmodo\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m     \u001b[0marchivo\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Esto es una nueva linea\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m     \u001b[0marchivo\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mFileNotFoundError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mUnsupportedOperation\u001b[0m: not writable"]}]},{"cell_type":"code","source":[],"metadata":{"id":"H06lcTZ3LuD5"},"execution_count":null,"outputs":[]}],"metadata":{"colab":{"provenance":[]},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.1"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"1606ed296fe21ab67c1d4b49f3f22d72247524c93f58d404930dbd4d15d6017c"}}},"nbformat":4,"nbformat_minor":0}